### PR TITLE
Add FORD as a Intelligent Provider

### PR DESCRIPTION
**Pull request by grantbevis**
Hey,

I've taken a quick stab at this, the unit tests ran fine but I had an issue with the integration tests. At first it wanted my `ACCOUNT_ID` as a envar which I provided then it was moaning about a GAS_MRPN? Something un-related to Electricity either way.

I'm hoping this will resolve https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/993

Any feedback is greatly appreciated

Kind regards,
Grant

### CODE REVIEW

**Comment by BottlecapDave** [comment]
All looks good to me. The integration tests don't really touch these functions and are aimed at my account (as that's the only one I have access to) so can be ignored in this scenario. 

Just want to double check that all enabled features are available within the app for this provider?

**Comment by grantbevis** [comment]
Yeah the features all seemed to be there the only one of the bools I wasn’t totally sure on was if I can turn smart charging on or off for the Octopus “device”, I can set all the other settings though.

Background is the device is my car (Ford Mustang Mach-E) and not a charger. Octopus seem to do some magic with API calls over to FordPass to stop/start the car charging. 

I can see the schedule/charging plan when plugged in, I can set a limit and ready by time etc. 

I wondered if there was a API call I could make in postman against my Octopus account to double check the features enabled by their response?

Kind regards 
Grant

**Comment by BottlecapDave** [comment]
The smart charging on/off feature to my knowlege is where you can turn intelligent on/off within the app so that OE doesn't calculate dispatch times and have OE charge the car. I'm not sure where it usually is within the app though. Its turned off for Ohme because this can apparently break the integration.

**Comment by grantbevis** [comment]
I've looked through the OE app again and there's no ability for me to switch off smart charging, looking at the python code again I don't think I'll need to make any changes?

**Comment by BottlecapDave** [comment]
If available, an option should be available as specified in https://myenergi.info/viewtopic.php?p=116829#p116829.

If it isn't available, then you'll need to update `get_intelligent_features` within `custom_components\octopus_energy\intelligent\__init__.py` to include a record similar to OHME for Ford, but with everything turned on other than smart charge (e.g. return IntelligentFeatures(False, True, True, True, True, False))

You'll also need to update the docs (`_docs\entities\intelligent.md`) to specify the Smart Charge switch isn't available for FORD

**Comment by grantbevis** [comment]
Thanks for the forum link, yep as the post says it's buried deep in the settings in a non-obvious place but it's there:

image

So the PR should be good to go as is I think

**Comment by BottlecapDave** [comment]
Cool. Thanks for the addition and investigation.

**Comment by grantbevis** [comment]
Thanks for merging the PR and happy to contribute. What's the process for getting this released to HACS so I can test the updated integration?

**Comment by grantbevis** [comment]
> Thanks for merging the PR and happy to contribute. What's the process for getting this released to HACS so I can test the updated integration?

@BottlecapDave sorry to nag, did you see this comment matey?

**Comment by BottlecapDave** [comment]
Didn't see this. It will be available in the next release, which is pending some other changes. I hope to get a beta release out later this week/early next week.

**Pull request merged**
